import type { Metadata } from "next";
import "./globals.css";
import Navbar from './components/Navbar';
import { Toaster } from "react-hot-toast"; 
import { AppProvider } from "./Context/AppProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <Toaster />  
          <Navbar />
        {children}
        </AppProvider>
      </body>
    </html>
  );
}
